services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pr_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate:v4.17.0
    restart: no
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://postgres:postgres@db:5432/pr_service?sslmode=disable"
      - "up"
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://postgres:postgres@db:5432/pr_service?sslmode=disable
      - PORT=8080
    depends_on:
      - migrate
  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      SWAGGER_JSON_URL: /openapi.yaml
      BASE_URL: /
      URLS_PRIMARY_NAME: "PR Service API"
    depends_on:

      - api
